driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: centos-6.8
- name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[yum-percona::default]
