name              'yum-percona'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures the Percona Yum repository'
version           '3.2.4'
source_url        'https://github.com/sous-chefs/yum-percona'
issues_url        'https://github.com/sous-chefs/yum-percona/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
